### PR TITLE
Add dynamic WinForms example

### PR DESCRIPTION
**Pull request by Krutonium**

### CODE REVIEW

**Comment by mfkl** [comment]
What do you mean by dynamic?

**Comment by jeremyVignelles** [comment]
I called it dynamic as opposed to the control that you drop in the designer. Any other name suggestion

**Comment by jeremyVignelles** [comment]
The problem with Dynamic/DynamicUI is that you don't get immediately what the sample is about. is it a sample of controls that are replaced dynamically at runtime? We need to read a readme to understand.

If it was WPF, I'd call that "code behind" but  I don't know how it's called in WinForms

**Comment by jeremyVignelles** [comment]
`.InitWithCode`?

**Comment by mfkl** [comment]
Also called code behind for WinForms I assume.

**Comment by Krutonium** [comment]
I don't know *what* you would want to call it, `DesignedWithCode`?

**Comment by jeremyVignelles** [comment]
"Designed" means "with the designer" for me. I like `InitWithCode` more

**Comment by jeremyVignelles** [comment]
Replaced by #510, thanks

**Pull request closed without merging**
