### PR TITLE
Update Form1.cs VlcDirectory

### PR DESCRIPTION
**Pull request by graysuit**
No need to use too long strings for just finding current directory,
Visit for Getting current directory: https://stackoverflow.com/a/34648431/11390822
Path.combine sometimes gives errors.
You can add this string to your other samples as well.
Thanks I love Vlc.dotnet

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
Why not, I'm not against that change, but I always tend to use Path.Combine() everywhere there is path concatenations.

As far as I know it can only throw if one of the path component is null or invalid, which is good for safety. Do you see anywhere else it can crash?

You need to fix your code though, because you are missing parenthesis around the ternary condition, which made the CI fail.

Otherwise, I'm OK to apply that chang

**Comment by jeremyVignelles** [comment]
Why not, I'm not against that change, but I always tend to use Path.Combine() everywhere there is path concatenations.

As far as I know it can only throw if one of the path component is null or invalid, which is good for safety. Do you see anywhere else it can crash?

You need to fix your code though, because you are missing parenthesis around the ternary condition, which made the CI fail.

Otherwise, I'm OK to apply that chang

**Comment by graysuit** [comment]
<h2> Should I use PATH.COMBINE ?</h2>

- I forget the error that was thrown by **Path.Combine**. ERROR was started with something like **STRING is abc**.
- It depends on you whether you want to use **PATH.COMBINE** or not,
- But my opinion is that you should not use extra things. It will cause **burden and difficult to understand** for user,

You can use either [Recommended]:
`var libDirectory = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory + @"libvlc\" + IntPtr.Size == 4 ? "win-x86" : "win-x64");`

OR
`var libDirectory = new DirectoryInfo(Path.Combine({@AppDomain.CurrentDomain.BaseDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"}));`


<h2> Don't use long/extra strings:</h2>

- Other thing is that 3--4 strings have been used for just finding current directory,
- Using this code will simplify the code.
- I don't use C# , so it can contain errors.

**Comment by jeremyVignelles** [comment]
Hi, sorry for the delay.

I will not merge this PR as-is because:
- It does not build
- It only addresses the case for one sample
- Still hesitating on the choice of AppDomain, which is a thing of the past in my understanding, `AppContext.BaseDirectory` is more future-proof if I understood correctly, but might not be very backward-compatible
- Still unsure about not using Path.Combine
- It does not fix any bug, the effort is not worth it, as I tend to phase out this project in favor of LibVLCSharp.

Thanks anyway for your contribution !

**Comment by graysuit** [comment]
Path.combine is best,
I have learned now,
It combines unordered path.

And I was just made this pull request,
To minify all code,
The more little code the more better performance.

And you have said tons of time that LibVLCsharp will take this repos place,
But I don't think,
Because they don't have even issues panel,
But you have issues panel,
And you solved many peoples issue,

And thanks again for making this great thing.

**Pull request closed without merging**
