### PR TITLE
Added support for setting subtitle files to MediaPlayer

### PR DESCRIPTION
**Pull request by eadwinCode**

### CODE REVIEW

**Comment by Traderain** [comment]
Can you make it accept streams? It would be much more usefull in some projects.

**Comment by eadwintoochos** [comment]
Do you mean subtitle stream??.. What I added was just a way you can add a subtitle file supported by vlc to the player. The vlc library still does all the work.

**Comment by jeremyVignelles** [comment]
I was just looking at it, but it seems that libvlc_video_set_subtitle_file is now deprecated :
https://github.com/videolan/vlc-3.0/blob/115c4a55a728ac504f8285f70d19c56ed9d873bb/include/vlc/deprecated.h#L128

**Comment by jeremyVignelles** [comment]
@eadwintoochos : Please reimplement your PR using libvlc_media_player_add_slave
@Traderain : It looks like it is not possible in libvlc itself, so what you are asking for can't be implemented that way.

**Comment by jeremyVignelles** [comment]
I'm now closing this PR since there are conflicts and because libvlc_media_player_add_slave should be used instead.
Please create another PR with the asked changes if you feel this is important.

**Pull request closed without merging**
