### PR TITLE
change wpf VlcControl using mvvm

### PR DESCRIPTION
**Pull request by xue-blood**
covert VlcControl.cs as a viewmodel, so now can use it by databinding.

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
Instead of making VlcControl implement INPC, I'd rather introduce a real ViewModel (as in M-V-VM) that can be reused in other GUI libraries.
What do you think?

**Comment by amaitland** [comment]
As an interested party, just having a look over this, for controls typically `DependencyProperty` would be used in `WPF`.

I'm working on a `WPF` implementation of the control (still a `WinFormsHost` under the hood for now), here's a snippet below. When it reaches a mature enough point I'll submit a `PR` if people show interest.

```c#
/// <summary>
/// Get/set movie position as percentage between 0.0 and 1.0.
/// </summary>
public float Position
{
	get { return (float)GetValue(PositionProperty); }
	set { SetValue(SourceProperty, value); }
}

/// <summary>
/// The position property
/// </summary>
public static readonly DependencyProperty PositionProperty = DependencyProperty.Register("Position", typeof(float), typeof(VlcControl), new UIPropertyMetadata(-1f, OnPositionChanged));

/// <summary>
/// Handles the PositionChanged event.
/// </summary>
/// <param name="sender">The sender.</param>
/// <param name="args">The <see cref="DependencyPropertyChangedEventArgs"/> instance containing the event data.</param>
private static void OnPositionChanged(DependencyObject sender, DependencyPropertyChangedEventArgs args)
{
	var owner = (VlcControl)sender;
	var oldValue = (float)args.OldValue;
	var newValue = (float)args.NewValue;

	owner.OnPositionChanged(oldValue, newValue);
}

/// <summary>
/// Called when position changed.
/// </summary>
/// <param name="oldValue">The old value.</param>
/// <param name="newValue">The new value.</param>
protected virtual void OnPositionChanged(float oldValue, float newValue)
{
	if (mediaPlayer == null || newValue < 0 || newValue > 1)
	{
		return;
	}

	mediaPlayer.Position = newValue;
}
```

```c#
private void OnPositionChangedInternal(object sender, VlcMediaPlayerPositionChangedEventArgs e)
{
	UiThreadRunAsync(() =>
	{
		SetCurrentValue(PositionProperty, e.NewPosition);
	});
}
```

```c#
/// <summary>
/// Runs the specific Action on the Dispatcher in an async fashion
/// </summary>
/// <param name="action">The action.</param>
/// <param name="priority">The priority.</param>
private void UiThreadRunAsync(Action action, DispatcherPriority priority = DispatcherPriority.DataBind)
{
	if (Dispatcher.CheckAccess())
	{
		action();
	}
	else if (!Dispatcher.HasShutdownStarted)
	{
		Dispatcher.BeginInvoke(action, priority);
	}
}
```

**Comment by jeremyVignelles** [comment]
Hi @amaitland , thanks for joining in. Feel free to join the discussion on gitter.

I am currently in a discussion with VLC authors and we are looking to make an "officially recommended .net library for VLC".
That means we want to create a ui-agnostic core library, that looks like the original libvlc + .net-specific tools (like properties, events, dependency properties...). On top of that, one library per UI framework would be created.
The current mindset is not to create a WPF-specific thing, but rather to improve the core (.net standard) to make things easier to use without GUI, and then have a tiny UI-control specific to the platform.

You are welcome to submit PRs in that way, but keep in mind that I will probably be working on this soon.

**Comment by amaitland** [comment]
> I am currently in a discussion with VLC authors and we are looking to make an "officially recommended .net library for VLC".

Great news 👍 

> and then have a tiny UI-control specific to the platform.

What I'm proposing already fits with this model unless I'm missing something??? I'd say in reality you'll have to upgrade the expectation of **tiny** to **medium** sized control for `WPF` to support `DependencyProperties/Commands/Events` and all the other plumbing that will be required. 

> You are welcome to submit PRs in that way, but keep in mind that I will probably be working on this soon.

I have an immediate requirement, so waiting isn't a realistic option at this point in time. The implementation I have in mind should be easily ported to your new proposed `VLC.Net` wrapper, so some code can likely be integrated into your implementation 😄 

When I have time I'll jump on gitter and see what the updated state of play is 👍 Thanks for the quick reply!

**Comment by jeremyVignelles** [comment]
Closing this for now, too much incompatibles changes. We need a new implementation.

**Pull request closed without merging**
