### PR TITLE
Added the `ResetMedia` method

### LINKED ISSUE #535: Add the ability to call `SetMedia(null)`
Currently, we cannot call `SetMedia()` with a null argument to reset the current media.

We should allow that use case because vlc supports it:
https://github.com/videolan/vlc-3.0/blob/738da6c2737d2da93b24b7cce47944d45d10d8d3/lib/media_player.c#L898

Original question:
https://stackoverflow.com/questions/55191158/how-to-clear-vlcmediaplayer-media-source

### PR DESCRIPTION
**Pull request by jeremyVignelles**
Fixes #535

### CODE REVIEW

**Comment by LouisCPro** [comment]
Hi All,

ResetMedia stop the video but does not clear the image in vlcControl ! Any tux ?

Regards,

**Comment by jeremyVignelles** [comment]
This is not the proper place to ask questions, open an issue instead.
Did you try Stop()?

**Comment by theemprator** [comment]
Hi,
I'm using vlc.net.core to convert some files then open these files in strream writer.
the stream writer fails to load the files because it is used by vlc
I tried resetmedia() , stop() , GetMedia().Dispose() and disposing the player itself all of  these didn't work and the file is still opened

**Comment by jeremyVignelles** [comment]
@theemprator : Please open a new issue for that.

Do you create a media instance yourself or do you use the Play() overload that creates the Media for you? If you create the media yourself, do not forget to Dispose() it, but `GetMedia().Dispose()` is useless, it creates a new reference to a media, and destroys it.

**Pull request merged**
