### PR TITLE
Reworked VlcManager architecture

### LINKED ISSUE #389: throw an exception when trying to modify libvlc options after start
Several issues posted here are from users wondering why they can't edit vlc options after startup, it shouldn't be possible to edit options after media player creation.

### LINKED ISSUE #482: AccessViolationException during disposing multiple instances
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : _VideoLAN.LibVLC.Windows_ from nuget package (version 3.0.4), machine runs on x64
- **.net version** : 4.7.1
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64

# Summary

In case when multiple instances of `VlcMediaPlayer` are in use, it's not possible to dispose they correctly, because `Dispose()` will throw `System.AccessViolationException` 

# Scenario to reproduce issue:

1. Create more than one instance of `VlcMediaPlayer`. `SetMedia `and `Play` for each of they
2. `Stop()` and `Dispose()` first instance
3. Try to stop and dispose second instance

**Result:** `System.AccessViolationException` was thrown during disposing second instance

**Stacktrace**
```
at Vlc.DotNet.Core.Interops.VlcManager.GetMediaPlayerEventManager(VlcMediaPlayerInstance mediaPlayerInstance)
  at Vlc.DotNet.Core.VlcMediaPlayer.UnregisterEvents()
  at Vlc.DotNet.Core.VlcMediaPlayer.Dispose(Boolean disposing)
  at Vlc.DotNet.Core.VlcMediaPlayer.Dispose()
  at VLCTest.Program.Main(String[] args)
```

# Example code that reproduce issue:

```

static void Main(string[] args)
{
    var currentDirectory = Path.GetDirectoryName(
    System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase);

    currentDirectory = currentDirectory.Substring(6);

    var libDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));

    var destination1 = Path.Combine(currentDirectory, "record1.mp4");
    var destination2 = Path.Combine(currentDirectory, "record2.mp4");

    var mediaPlayer1 = new VlcMediaPlayer(libDirectory);
    var mediaPlayer2 = new VlcMediaPlayer(libDirectory);

    var mediaOptions1 = new[]
    {
		$":sout=#file{{dst={destination1}}}",
		":sout-keep"
    };
    var mediaOptions2 = new[]
    {
		$":sout=#file{{dst={destination2}}}",
		":sout-keep"
    };

    var fileInfo1 = new FileInfo("test1.sdp");
    var fileInfo2 = new FileInfo("test2.sdp");

    mediaPlayer1.SetMedia(fileInfo1, mediaOptions1);
    mediaPlayer2.SetMedia(fileInfo2, mediaOptions2);

    mediaPlayer1.Play();
    mediaPlayer2.Play();

    Console.WriteLine("Press any key to stop");
    Console.ReadKey();

    mediaPlayer1.Stop();
    mediaPlayer2.Stop();

    mediaPlayer1.Dispose();
    mediaPlayer2.Dispose();
}
```

**I found workaround for this issue:** you must create separate folder of `libvlc` libraries for each instance of `VlcMediaPlayer`

### PR DESCRIPTION
**Pull request by jeremyVignelles**
to ensure proper loading/unloading of libvlc*.dll

Fixes #482 
Fixes #389 
Replaces #486 

A few words about the implementation : 
- Removed useless `VlcInteropsManager` abstract class
- Introduced a VlcLibraryLoader class : It loads the DLL files and DLL functions. Static methods are there to ensure that only one instance is there per path, and that the DLL is properly unloaded when it's not needed anymore.
- VlcManager is not tied to a dll path anymore (it's VlcLibraryLoader's job). Instead it's tied to a VlcInstance, i.e. libvlc_new
- libvlc instances are not cached anymore: This means that two different players can (will by default) use two different libvlc instances, each having potentially different media player options
- VlcManager.CreateNewInstance does not exist anymore : instead, arguments are passed to VlcManager's constructor and libvlc instance is created in the constructor.
- This means that EnsureVlcInstance is not needed anymore.

- Behavior changed : No options are passed to the MediaPlayer by default. To restore previous behavior, set:

```
#if DEBUG
            var option = new[]
            {
                "--extraintf=logger",
                "--verbose=2"
            };
#else
            var options = new[]
            {
                "--quiet"
            };
#endif
```

- MISC : WinForms Control now throws on invalid VlcMediaPlayerOptions/VlcLibDirectory usage.

/cc @dilandau2001

### CODE REVIEW

**Comment by dilandau2001** [comment]
Hi. I saw your message. I am currently without computer. I would like to check out your branch to give it a look but it would not be soon.

**Comment by jeremyVignelles** [comment]
Thanks for your answer. I'm currently out for holidays and will return on december the 1st.
I'm interested in your feedback anyway, even if it's later, don't worry

**Comment by jeremyVignelles** [comment]
Hi @dilandau2001 , any time for a review?

**Comment by dilandau2001** [comment]
Today, I will give it a try. sorry for the delay

**Comment by dilandau2001** [comment]
I did a test with this code.

I used sample: MultiplePlayers.
The test steps were:
1- Create 1 player
2- Destroy it
3- Get memory snapsot

I did it multiple times.

I could reproduce a small and consistent leak but I haven't being able yet to identify the leak as apparently handlers are bein unregistered correctly.

image

Also VlcControl.EndInit has become a bit slower than before. Don't know the reason either. I would sepparate the part of the code that requires to run in the ui thread (apparently only the handle assingn) from the part of the code that can run in a different thread so the time the ui is blocked is reduced to the minimum.

**Comment by jeremyVignelles** [comment]
Thanks for the review!

> Also VlcControl.EndInit has become a bit slower than before.

Seems quite normal : the libvlc instance is not shared anymore, which means we need to call `libvlc_new` each time, but which brings the benefit of being able to pass different parameters.

You can still create a new media player with a shared VlcManager if you want, because this constructor is now public. https://github.com/ZeBobo5/Vlc.DotNet/pull/490/files#diff-478680d15152ff2c027403f8f9ee05c9R24.

For the leak, I did try that and noticed the same thing. However, I'm not a memory leak expert, and concluded that the leak wasn't meanignful and was likely caused by the runtime or the environment and was normal.

If you think that something is wrong, we will need to dig deeper. Can that be an issue on libvlc's side?

**Comment by jeremyVignelles** [comment]
>  I would sepparate the part of the code that requires to run in the ui thread (apparently only the handle assingn) from the part of the code that can run in a different thread so the time the ui is blocked is reduced to the minimum.

Is it really long? Do we really need to do something about it? Spawning a thread/awaiting something in the constructor feels dangerous (race conditions, hard error catching...) for me without a good reason.

**Comment by dilandau2001** [comment]
Testing performance, starting and closing players several times I could reproduce the following crash:

Faulting application name: Samples.WinForms.MultiplePlayers.exe, version: 0.0.0.0, time stamp: 0xba087546
Faulting module name: ntdll.dll, version: 10.0.17134.376, time stamp: 0x60d78cf9
Exception code: 0xc0000374
Fault offset: 0x00000000000f4d7b
Faulting process ID: 0x14e8
Faulting application start time: 0x01d490da2698128c
Faulting application path: D:\PROJECTS\Vlc.DotNetUpdate\src\Samples\Samples.WinForms.MultiplePlayers\bin\Debug\Samples.WinForms.MultiplePlayers.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: afa3dbbd-e0d2-4804-ab04-438a0efc6442
Faulting package full name: 
Faulting package-relative application ID:

**Comment by dilandau2001** [comment]
I did a small variation of the test:

Living always one player running. 
1 - Create a second player,
2 - Destroy it
3 - Get snapshot:


With x64 VLC 3.04 version results:
image

ntdll.dll crash when 10 players playing.

With x64 VLC 2.2.4 version results:

image

memory still leaks.
But at least there is no ntdll.dll crash.

The thing is, I think the previous code was not leaking over time.
I will have to test if over time (long time) the memory stabilizes

**Comment by dilandau2001** [comment]
I was wrong, old code leaks the same amount...
At least it seems to be under control because it is not the exact same amount per closed player.
A good test would be to leave a test running for a day opening and closing players.

**Comment by dilandau2001** [comment]
> Is it really long? Do we really need to do something about it? Spawning a thread/awaiting something in the constructor feels dangerous (race conditions, hard error catching...) for me without a good reason.

Well, it depends what is the source of the leak. If it is leaking handlers then that will eventually rise an outofmemory exception. If it is rubbish for the GC to work with then you can survive with it.

**Comment by jeremyVignelles** [comment]
The architecture of this PR is where I want to go with Vlc.DotNet : the Libvlc instance is not shared anymore, allowing it to be released properly and passing different options.

Sharing libvlc instance leaks only one instance per run, but that doesn't mean that the code is better IMHO.

We need to fix that crash before merging

**Comment by dilandau2001** [comment]
Can you reproduce the crash in your environment?... just opening 10-15 players with Vlc 3.0.4.
And it does not crash with 2.2.4.
If it happens to you as well I would say it is an issue of vlclib itself as ntdll.dll is something quite deep in Windows system.

**Comment by jeremyVignelles** [comment]
I didn't have time to try it yet. ntdll doesn't really mean anything since it's used everywhere...

**Comment by jeremyVignelles** [comment]
Despite my tests, I couldn't reproduce this on my windows 10... Anyone else reproduces the crash? Anyone else can try this?

I launched a debug session of `Sample.WinForms.MultiplePlayers`, added many players, removed many players, repeated... no crash...

**Comment by jeremyVignelles** [comment]
@dilandau2001: which windows version?

**Comment by dilandau2001** [comment]
I did my tests with Windows 10

**Comment by mfkl** [comment]
@dilandau2001 Can you share your full code for repro please?

**Comment by hasanghaddar** [comment]
@jeremyVignelles  I am facing this issue also , and tested on Windows 10 and Windows server 2018 r2

**Comment by jeremyVignelles** [comment]
I'm back with this PR after a long time!

@dilandau2001 , After testing, I disagree with that part:
> Also VlcControl.EndInit has become a bit slower than before. 

With this code in MultiplePlayers.Forms1:

```cs
                    panel.Controls.Add(player);
                    var sw = new Stopwatch();
                    sw.Start();
                    player.EndInit();
                    Debug.WriteLine($"Elapsed {sw.ElapsedMilliseconds}ms");
```

Before this PR:
> Elapsed 595ms
> Elapsed 468ms
> Elapsed 1037ms
> Elapsed 1142ms

After:
> Elapsed 422ms
> Elapsed 9ms
> Elapsed 10ms
> Elapsed 12ms


I guess we could do better if we passed the media player to the control, but I think it is acceptable as-is.

I still can't reproduce your crash... can you try to clean your code? Are you on a x86 windows? I can't figure out what's the difference between your machine and mine. If anyone has a clue, he's welcome...

**Comment by dilandau2001** [comment]
I will do a retry as soon as I can.
Mine is a Windows 10 x64 SO

**Comment by dilandau2001** [comment]
Hello

I gave it another try.
I don't see evident memory leak nor event handlers left behind so that is good news. 
But I could consistently reproduce the crash. 
Using this pull code with Vlc libs coming from VLC 3.0.6.

This is how I did it:
[Project 1.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/2800907/Project.1.zip) : Video of error.

Reproduction steps:
- Open 12-14 players very fast of a local file
- let them play until end of video, it gets frozen. :input-repeat=-1 does not work fine with small videos.
- Close them very fast too.

Notes:
The video is quite small, less than 10 seconds and it gots frozen at the end of it as loop does not work fine with short videos.

Tips:
To be honest, what I finally came up doing for multiple players was to run each player on its own executable and link each window on the desirable parent. So if one player crashes main application can survive and restart it, and also you are no longer limitted by one single process memory limit.

**Comment by jeremyVignelles** [comment]
Hello, thanks for the explanations, will try that. is that possible that the crash comes from libvlc itself? frozen video is not a good sign.
 does the crash happen with the current develop version?

Your solution of making child process is good for video wall applications (I'm using this technique too) but doesn't apply to all cases, when video are embedded in a GUI for example.

**Comment by dilandau2001** [comment]
Well I actually embed the videos inside my Gui using Win32 SetParent functions and similar things. Only for Windows though.

Regarding the crash. It did not happen in vlc 2.2.4 so it seems something from vlc itself.

**Pull request merged**
